### ISSUE TITLE
Hi fellow bot framework creator

### ISSUE THREAD

**Issue by dempfi** [RationalAnimal/vui-ad-hoc-alexa-recognizer#3242]
@RationalAnimal I tried really hard to find you public contact but it seems you prefer to be in shadows :)

Anyways, I stumbled upon your npm package when was looking for nlp tools for to extend my bot framework and I was astonished by the amount of work you already did. Congrats 🎉 

Saying that, I have a proposal to collaborate and maybe integrate our tools and create something better together then we would do otherwise on our own.

If you're interested, please connect with via email dempfi@yahoo.com.

---
P.S. It seems from your name you might be speaking Russian, if that's the case, I would be thrilled to continue dialogue in Russian.

**Comment by RationalAnimal** [comment]
Hi there

I'll respond in private email; closing this issue.

Thank you
Ilya
