### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by KB1RMA** [RationalAnimal/vui-ad-hoc-alexa-recognizer#420]
Hey - Do you think you'll put tutorials up on a site somewhere?

**Comment by RationalAnimal** [comment]
i'll probably start doing something like that soon.  The code is getting pretty functional and it might make sense now to add more documentation and/or tutorials.

**Comment by SanityLacking** [comment]
This module seems really useful. When going through the tutorials just now I found an error in the syntax of the first tutorial [here](https://rationalanimal.github.io/vui-ad-hoc-alexa-recognizer/Tutorials/HelloWorld/), The example text for the intents.json file is missing a square bracket which when pasted in and run with the generator command gives an "Unable to load Intents file" error.
`{
  "intents": [
    {
      "intent": "GreetingIntent",
      "slots": []
    }
}`
I believe should be, 
`{
  "intents": [
    {
      "intent": "GreetingIntent",
      "slots": []
    }
 ]
}`

I look forward to getting to use the module more!

**Comment by RationalAnimal** [comment]
Thank you for pointing this out - should be fixed now.
